# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/jewel/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/htc/jewel/proprietary/bin/akmd:system/bin/akmd \
	vendor/htc/jewel/proprietary/bin/bma150_usr:system/bin/bma150_usr \
	vendor/htc/jewel/proprietary/bin/rild:system/bin/rild \
	vendor/htc/jewel/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
	vendor/htc/jewel/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
	vendor/htc/jewel/proprietary/lib/libhtc_rilhook.so:system/lib/libhtc_rilhook.so \
	vendor/htc/jewel/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
	vendor/htc/jewel/proprietary/lib/libimu.so:system/lib/libimu.so \
	vendor/htc/jewel/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
	vendor/htc/jewel/proprietary/lib/libmllite.so:system/lib/libmllite.so \
	vendor/htc/jewel/proprietary/lib/libMLTransition.so:system/lib/libMLTransition.so \
	vendor/htc/jewel/proprietary/lib/libmpl.so:system/lib/libmpl.so \
	vendor/htc/jewel/proprietary/lib/libmpl_jni.so:system/lib/libmpl_jni.so \
	vendor/htc/jewel/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/htc/jewel/proprietary/etc/agps_rm:system/etc/agps_rm \
	vendor/htc/jewel/proprietary/bin/charging:system/bin/charging \
	vendor/htc/jewel/proprietary/bin/mpdecision:system/bin/mpdecision \
	vendor/htc/jewel/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/htc/jewel/proprietary/bin/netsharing:system/bin/netsharing \
	vendor/htc/jewel/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/htc/jewel/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/htc/jewel/proprietary/bin/thermald:system/bin/thermald \
	vendor/htc/jewel/proprietary/bin/zchgd:system/bin/zchgd \
	vendor/htc/jewel/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
	vendor/htc/jewel/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
	vendor/htc/jewel/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	vendor/htc/jewel/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
	vendor/htc/jewel/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
	vendor/htc/jewel/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
	vendor/htc/jewel/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
	vendor/htc/jewel/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
	vendor/htc/jewel/proprietary/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
	vendor/htc/jewel/proprietary/etc/firmware/modem.b07:system/etc/firmware/modem.b07 \
	vendor/htc/jewel/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b00:system/etc/firmware/modem_fw.b00 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b01:system/etc/firmware/modem_fw.b01 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b02:system/etc/firmware/modem_fw.b02 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b03:system/etc/firmware/modem_fw.b03 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b04:system/etc/firmware/modem_fw.b04 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b05:system/etc/firmware/modem_fw.b05 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b06:system/etc/firmware/modem_fw.b06 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b07:system/etc/firmware/modem_fw.b07 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b08:system/etc/firmware/modem_fw.b08 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b09:system/etc/firmware/modem_fw.b09 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b10:system/etc/firmware/modem_fw.b10 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b13:system/etc/firmware/modem_fw.b13 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b14:system/etc/firmware/modem_fw.b14 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b21:system/etc/firmware/modem_fw.b21 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b22:system/etc/firmware/modem_fw.b22 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b23:system/etc/firmware/modem_fw.b23 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b25:system/etc/firmware/modem_fw.b25 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b26:system/etc/firmware/modem_fw.b26 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b29:system/etc/firmware/modem_fw.b29 \
	vendor/htc/jewel/proprietary/etc/firmware/modem_fw.mdt:system/etc/firmware/modem_fw.mdt \
	vendor/htc/jewel/proprietary/etc/firmware/q6.b00:system/etc/firmware/q6.b00 \
	vendor/htc/jewel/proprietary/etc/firmware/q6.b01:system/etc/firmware/q6.b01 \
	vendor/htc/jewel/proprietary/etc/firmware/q6.b03:system/etc/firmware/q6.b03 \
	vendor/htc/jewel/proprietary/etc/firmware/q6.b04:system/etc/firmware/q6.b04 \
	vendor/htc/jewel/proprietary/etc/firmware/q6.b05:system/etc/firmware/q6.b05 \
	vendor/htc/jewel/proprietary/etc/firmware/q6.b06:system/etc/firmware/q6.b06 \
	vendor/htc/jewel/proprietary/etc/firmware/q6.mdt:system/etc/firmware/q6.mdt \
	vendor/htc/jewel/proprietary/lib/libdiag.so:system/lib/libdiag.so \
	vendor/htc/jewel/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/htc/jewel/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
	vendor/htc/jewel/proprietary/lib/libidl.so:system/lib/libidl.so \
	vendor/htc/jewel/proprietary/lib/libqdi.so:system/lib/libqdi.so \
	vendor/htc/jewel/proprietary/lib/libqdp.so:system/lib/libqdp.so \
	vendor/htc/jewel/proprietary/lib/libqmi.so:system/lib/libqmi.so \
	vendor/htc/jewel/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
	vendor/htc/jewel/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
	vendor/htc/jewel/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
	vendor/htc/jewel/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
	vendor/htc/jewel/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
	vendor/htc/jewel/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/htc/jewel/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
	vendor/htc/jewel/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
	vendor/htc/jewel/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	vendor/htc/jewel/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
	vendor/htc/jewel/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
	vendor/htc/jewel/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
	vendor/htc/jewel/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
	vendor/htc/jewel/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
	vendor/htc/jewel/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
	vendor/htc/jewel/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
	vendor/htc/jewel/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt
